/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.CajaFuerteMain;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args) {
        
        Scanner miScan = new Scanner(System.in);
        
        
        CajaFuerte miCajaCaudales;
        miCajaCaudales = new CajaFuerte(); //Se crea miCajaCaudales como objeto de la clase CajaFuerte
   
        int select; //opción seleccionada por teclado
        
        String oldPass; //contraseña antigua
        String newPass; //contraseña nueva
        
        do{
            
            System.out.println("\n1. Asignar nueva combinación");//Los paréntesis son comportamientos.
            System.out.println("2. Abir caja fuerte");
            System.out.println("0. Salir");
            
            System.out.println("Seleccione una opción: ");
            select = miScan.nextInt();
            
            //CASO 1
            if(select == 1){
                
                System.out.println("Introduzca la contraseña: ");
                oldPass = miScan.next();
                
                System.out.println("Introduzca una nueva contraseña: ");
                newPass = miScan.next();
                
                if(miCajaCaudales.changePass(oldPass, newPass)){
                    System.out.println("Contraseña actualizada");
                }
                
            }    
            //CASO 2
            else if(select == 2){
                
                System.out.println("Introduzca la contraseña: ");
                newPass = miScan.next();
                
                //CONTRASEÑA CORRECTA
                if(miCajaCaudales.open(newPass)){ 
                    System.out.println("Caja fuerte abierta");
                }
                //CONTRASEÑA INCORRECTA
                else{
                    System.out.println("Combinación errónea");
                }
            }
            //CASO INEXISTENTE
            else if(select != 0){
                System.out.println("Esa opción no es correcta");
            }
        }while(select != 0);
        System.out.println("Cerrando programa. ¡Gracias por su uso!");
    }
}
